language: python
dist: xenial

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

env:
  matrix:
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'
  - DJANGO='django30' CMS='cms37'
  - DJANGO='django22' CMS='cms37'

services:
  - redis-server

install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PYVER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO-$CMS; fi"

script: COMMAND='coverage run' tox -e$TOXENV -- --verbose=2

before_install:
  - pip install -U setuptools tox>=1.8 coveralls codecov wheel pip
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 3.5
    env: DJANGO='django30' CMS='cms37'
  - python: 3.5
    env: TOXENV='docs'
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'
  - python: 3.6
    env: TOXENV='docs'
  - python: 3.6
    env: TOXENV='pep8'
  - python: 3.6
    env: TOXENV='isort'
  - python: 3.7
    env: TOXENV='docs'
  - python: 3.7
    env: TOXENV='pep8'
  - python: 3.7
    env: TOXENV='isort'


cache: pip


