# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

env:
  matrix:
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'
  - DJANGO='django111' CMS='cms35'
  - DJANGO='django111' CMS='cms34'


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO-$CMS; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e$TOXENV

before_install:
  - pip install -U setuptools tox>=1.8 coveralls codecov wheel pip
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 2.7
    env: TOXENV='docs'
  - python: 2.7
    env: TOXENV='pep8'
  - python: 2.7
    env: TOXENV='isort'
  - python: 3.4
    env: TOXENV='docs'
  - python: 3.4
    env: TOXENV='pep8'
  - python: 3.4
    env: TOXENV='isort'
  - python: 3.5
    env: TOXENV='docs'
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'


cache:
   directories:
     - $HOME/.pip-accel
     - $HOME/.cache/pip


